let g:dotfilesPath  = '~/dotfiles/nvim-partials/'
exe 'source' g:dotfilesPath . 'settings.vim'
exe 'source' g:dotfilesPath . 'plugins.vim'
exe 'source' g:dotfilesPath . 'mappings.vim'
exe 'source' g:dotfilesPath . 'abbreviations.vim'
exe 'source' g:dotfilesPath . 'statusline.vim'
exe 'source' g:dotfilesPath . 'ale.vim'
exe 'source' g:dotfilesPath . 'fzf.vim'
exe 'source' g:dotfilesPath . 'colorscheme.vim'
exe 'source' g:dotfilesPath . 'functions.vim'
