runtime! partials/plugins.vim
runtime! partials/settings.vim
runtime! partials/colorscheme.vim
runtime! partials/statusline.vim
runtime! partials/mappings.vim
runtime! partials/abbreviations.vim
runtime! partials/ale.vim
runtime! partials/functions.vim
runtime! partials/fzf.vim
