set -U fish_greeting

alias g="git"
alias gl="git pull"
alias gd="git diff"
alias glr="git pull -r"
alias gst="git status"
alias ggp="git push origin HEAD"
alias gti="git"
alias ga="git add"
alias gam="git commit --amend"
alias gaa="git add --all"
alias gcmsg="git commit --message"
alias glog="git log"
alias ys="yarn start"
alias yt="yarn test"
alias ytv="yarn test --verbose"
alias t="touch"
alias xx="exit"
alias d="docker"
alias drm="docker rm"
alias dst="docker stop"
alias dex="docker exec -it"
alias dps="docker ps"
alias dpsa="docker ps -a"
alias dpsaq="docker ps -aq"
alias lla="ls -la"
alias mk="make"

test $TERM != "screen"; and exec tmux
